### ISSUE TITLE
Completely port all Casper tests to Puppetter and Jest

### ISSUE THREAD

**Issue by tarelli** [openworm/geppetto-application#14]
Following the prototype [here](https://github.com/openworm/geppetto-application/issues/13) finish porting all Casper tests of Geppetto application

**Comment by filippomc** [comment]
Hi @jrmartin are you planning to do all the tests? Maybe @afonsobspinto may take some!

**Comment by jrmartin** [comment]
@filippomc I was planning on doing them all, but the plan can change. What did you have in mind for splitting? 

There's still lots of test to migrate from DefaultProjectsTests.js. All of PersistenceTests.js (with PersistenceTestsLogic.js) , NeuronalProjectsTests.js (with NeuronalTestsLogic.js), GeppettoModelTests.js and LiveTests.js. 

Split proposal: 

Whomever continues with DefaultProjectsTests.js, should probably also do NeuronalProjectsTests.js (with NeuronalTestsLogic.js), since the former also uses test functions from NeuronalTestsLogic.js.  Maybe you @afonsobspinto can do this? Here are some instructions on how to start from Facundo https://github.com/openworm/org.geppetto.docs/blob/test-puppeteer/source/casper_tests.md . The branch we want to checkout for geppetto-application is 'test-puppeteer'.

I can take PersistenceTests.js (with PersistenceTestsLogic.js), GeppettoModelTests.js and LiveTests.js.

**Comment by filippomc** [comment]
@jrmartin seems a good plan! Thanks

**Comment by tarelli** [comment]
Done! Thanks @rodriguez-facundo @jrmartin @afonsobspinto
